### ISSUE TITLE
Does not generate keys, stops build

### ISSUE THREAD

**Issue by ijdfgh** [StefanBossbaly/CopperheadOS-Docker#3] opened 2018-05-10 13:09 UTC
The Docker image does not build keys, instead shuts down with no error.

>sudo docker run \\
>     -v /media/hdd/copperheados/src:/srv/src \\
>     -v /media/hdd/copperheados/chromium:/srv/chromium \\
>     -v /media/hdd/copperheados/ccache:/srv/ccache \\
>     -v /media/hdd/copperheados/keys:/srv/keys \\
>     -v /media/hdd/copperheados/tmp:/srv/tmp \\
>     -v /media/hdd/copperheados/zips:/srv/zips \\
>     -e USE_CCACHE=1 \\
>     -e SIGNATURE_SPOOFING="no" \\
>     -e DEVICE="walleye" \\
>     -e BUILD_TAG="OPM2.171019.029.B1.2018.05.08.01" \\
>     -e BUILD_ID="OPM2.171019.029.B1" \\
>     -e CHROMIUM_RELEASE_NAME="66.0.3359.126" \\
>     -e CHROMIUM_RELEASE_CODE="335912660" \\
>     -e NUM_OF_THREADS=6 \\
>     bflux/copperheados-docker

Output:

https://pastebin.com/n3TncTWt

Thank you.

**Comment by ijdfgh** [comment] 2018-05-10 15:49
Generated keys manually. The build is now progressing.

I think the issue lies in the fact that 'repo sync' does not complete for some reason. It tried to generate keys before any files were downloaded. As the make_key script is missing, it fails.

**Comment by StefanBossbaly** [comment] 2018-05-10 22:45
Ah I see. Thanks for the report. Will fix it in an upcoming commit.

**Comment by captainhook** [comment] 2018-05-12 17:46
I am getting the same with the latest changes. @ijdfgh did you do anything different/anything more? I've copied my keys over to /srv/keys/marlin/

**Comment by captainhook** [comment] 2018-05-12 18:11
I am encountering the same problem even with the latest commit. @ijdfgh did you do anything different/anything more? I've copied my keys over to /srv/keys/marlin/ and /media/hdd/copperheados/keys/, no difference.

**Comment by StefanBossbaly** [comment] 2018-05-13 02:27
Let me reinvestigate.

**Comment by StefanBossbaly** [comment] 2018-05-13 15:22
Running a sailfish build right now. Looks good so far. Will close it once the build completes. @captainhook can you pull the latest image and see if the issue is fixed on your end?

**Comment by zuranthus** [comment] 2018-05-19 19:09
I had the same problem before issue before when building for walleye. Now it works fine, the keys are generated and the build continues.

**Comment by StefanBossbaly** [comment] 2018-05-21 22:23
Closing as per @Kabuto85 comment.

@captainhook if the problem still persists feel free to comment with an update.

**Closed as completed by StefanBossbaly** 2018-05-21 22:23 UTC

**Comment by captainhook** [comment] 2018-05-22 13:44
Sorry, been rather busy. I'll test with the June release once it's out and provide feedback.
